### ISSUE TITLE
Neue Email Adresse für Kontaktanfragen

### ISSUE THREAD

**Issue by Tarnatos** [Freifunk-Nord/nord-startseite#10]
Derzeit gibt es für FFnord nur ffnord@freifunk.net, welche direkt auf die Mailingliste weiterleitet. Das führt gerade dann wenn der ML Admoin/Mod keine Zeit zum manuellen Freischalten hat zu ungeheuren Verzögerungen (siehe Email vom 26.11.2015 auf Ki-ML "[Freifunk-Kiel] Wie kann ich jemanden von FF Nord erreichen?")

Ich schlage daher vor, dass eine weitere Email Adresse eingerichtet wird (z.B. hallo {at} ffnord {.} net) welche dann entweder direkt auf die ML Adresse weiterleitet (trusted sender) oder aber als Mailverteiler an einen festgelegten Personenkreis weiterverteilt.

**Comment by MTRNord** [comment]
@DasNordlicht hat jetzt einen Mailserver laufen "kontakt@ffnord.net" und "admin@ffnord.net" wurden angelegt (siehe pull request #17 von @flecno)

**Comment by flecno** [comment]
@Tarnatos was stellst du dir unter trusted sender vor?

Von einem generellen Weiterleiten der Mails auf die Liste würde ich auch eher abraten. Damit würde zu viel Chaos auf die Liste gelangen und es könnten Informationen ungewollt dort landen, auch wenn der Absender unbekannt ist.
Ich würde einen Verteiler an einen Personenkreis bevorzugen. Dabei wäre ich allerdings glücklich darüber, wenn die Liste der Empfänger offen einsehbar ist. Was haltet ihr von einem CSV welches mit dem postfix o.ä. synchronisiert wird?

**Comment by DasNordlicht** [comment]
Ein kleines Team die diese Mail bearbeitet, kein CVS. 
Auf den Server läuft SOGo so das man Mail auch im Browser bearbeiten könnte oder als IMAP.
Was für Anfragen werden denn kommen meistens doch nur  "wie kann ich mitmachen"?
Ich glaube das wir die Anfragen nur an den passenden Ansprechpartner in die Fläche weiter geben müssen.

**Comment by Tarnatos** [comment]
@DasNordlicht

Das klingt doch nach einem Plan :)

**Comment by DasNordlicht** [comment]
Zur Zeit besteht noch ein Fehler im MX Record dort steht imap.ffnord.net und es mus nur ffnord.net lauten.

**Comment by DasNordlicht** [comment]
So Fehler beseitigt, die Mail kommen an. Kann dann also umgesetzt werden.

**Comment by Tarnatos** [comment]
Done.

https://github.com/ffnord/nord-startseite/commit/691dde63b525599f6bbcfefb9bd37fd7678c7bad
