### ISSUE TITLE
Hamburger Verweise im Knotenformular

### ISSUE THREAD

**Issue by Tarnatos** [Freifunk-Nord/nord-startseite#11]
Im Knotenformular muss der Link zur Knotenkarte auf http://mesh.ffnord.net/ geändert werden.

**Comment by rubo77** [comment]
Nein, die haupt-domain soll nord.freifunk.net blieben, also ist der link gut so

**Comment by rubo77** [comment]
closes #13 

> Nach Abschluss der Dateneingabe in das Knotenformular zeigt der Link zur Knotenkarte auf die Hamburger Map.

Siehe Bild!
http://www.xup.in/dl,16718132/Bildschirmfoto_vom_2015-11-29_11-37-38.png/

**Comment by rubo77** [comment]
Ich habe das in der

```
/home/fastdform/config.json
```

und den dienst neu gestartet:

```
service fastdform restart
```

**Comment by rubo77** [comment]
Falls man das mal selbst installieren will: 

https://github.com/ffnord/nord-ffffng/tree/readme

weiterentwickelt aus:
https://wiki.freifunk.net/index.php?title=Freifunk_Hamburg/FreifunkFastdForm
