### ISSUE TITLE
Hamburger Verweise im Knotenformular die 2.

### ISSUE THREAD

**Issue by Tarnatos** [Freifunk-Nord/nord-startseite#13]
Moin,

also langsam werde ich stinkig, ich sitze doch nicht hier rum und denke mir irgendwelche Issues aus! Wenn es nicht gewollt ist, dass Fehler hier aufgezeigt werden, dann spare ich mir das zukünftig!

Also nochmal:

Nach Abschluss der Dateneingabe in das Knotenformular zeigt der Link zur Knotenkarte auf die Hamburger Map.

Siehe Bild!
http://www.xup.in/dl,16718132/Bildschirmfoto_vom_2015-11-29_11-37-38.png/

**Comment by rubo77** [comment]
ok, falsch verstanden ;) reopened #11

**Comment by rubo77** [comment]
Ich finde es super, dass du hier fehler aufzeigst, bitte nicht falsch verstehen, wenn ich etwas schliesse, denke ich dass es erledigt ist.
