### ISSUE TITLE
TLS formular.ffnord.net

### ISSUE THREAD

**Issue by flecno** [Freifunk-Nord/nord-startseite#18]
Das Zertifikat für `formular.ffnord.net` passt nicht zur Domain. Ich denke, das könnte so manchen verunsichern. Kann hier "jemand" ein passendes Zertifikat beantragen und konfigurieren?

Außerdem würde ich vorschlagen, denn Webserver für diese Domain TLS-Only zu konfigurieren. Oder gibt es einen Grund diese Daten unverschlüsselt zu übertragen?

**Comment by flecno** [comment]
Ich hoffe ich erreiche hier die richtigen Personen. Denn ich kann in diesem Projekt keinen Zusammenhang zum Knotenformular erkennen, wurder aber hierauf verwiesen.

**Comment by rubo77** [comment]
hab ich auf der todo liste. ist auch schon beantragt

**Comment by Tarnatos** [comment]
Zur Erklärung:

Hier: https://github.com/ffnord/nord-ffffng

Können Issues zum Knotenformular eingereicht werden. Das macht in Bezug auf das FERTIGE Knotenformular aber keinen Sinn, da es sich dabei nur um die Source handelt.

Issues bezgl. der Seite ffnord.net lassen sich daher hier einfacher bearbeiten.
